version: '2'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        env_file:
            .env
        command: ["gunicorn", "-w", "1", "-t", "50", "app:app", "-b", "0.0.0.0:5000"]
