name: Deploy OpenTAK Portal
run-name: ${{ gitea.actor }} is deploying OpenTAK Portal
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: install docker cli
        run: |
          apt-get update
          apt-get install -y docker.io

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat >>~/.ssh/config <<END
          Host production
            HostName tak.kggdutchies.nl
            User root
            StrictHostKeyChecking no
          END

      - name: Deploy to production
        run: |
          ssh production << 'EOF'
            cd /root/services/opentak-onboarding-portal

            # Pull latest code
            git pull origin main

            # Get version info
            export GIT_COMMIT=$(git rev-parse --short=12 HEAD)
            export GIT_DATE=$(git log -1 --format=%cd --date=short)

            # Build and restart with new image
            docker compose build --build-arg GIT_COMMIT=$GIT_COMMIT --build-arg GIT_DATE=$GIT_DATE
            docker compose down
            docker compose up -d

            # Show status
            echo "=== Deployment Complete ==="
            docker compose ps

            # Verify the build
            echo "=== Verifying frontend bundle ==="
            docker compose exec -T web grep -o "Description" /app/frontend/dist/assets/*.js | wc -l

            echo "=== Recent logs ==="
            docker compose logs --tail=20 web
          EOF
