name: Build and Deploy OpenTAK Portal
run-name: ${{ gitea.actor }} is building and deploying OpenTAK Portal
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: docker:dind
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get version info
        id: version
        run: |
          echo "commit=$(git rev-parse --short=12 HEAD)" >> $GITEA_OUTPUT
          echo "date=$(git log -1 --format=%cd --date=short)" >> $GITEA_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/atak-onboarding-portal:${{ steps.version.outputs.commit }}
            ${{ secrets.DOCKER_USERNAME }}/atak-onboarding-portal:latest
          build-args: |
            GIT_COMMIT=${{ steps.version.outputs.commit }}
            GIT_DATE=${{ steps.version.outputs.date }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/atak-onboarding-portal:latest
          cache-to: type=inline

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat >>~/.ssh/config <<END
          Host production
            HostName tak.kggdutchies.nl
            User root
            StrictHostKeyChecking no
          END

      - name: Deploy to production
        run: |
          ssh production << 'EOF'
            cd /root/services/opentak-onboarding-portal

            # Pull latest code
            git pull origin main

            # Pull new image from Docker Hub
            docker compose pull

            # Restart with new image
            docker compose down
            docker compose up -d

            # Show status
            echo "=== Deployment Complete ==="
            docker compose ps

            # Verify the build
            echo "=== Verifying frontend bundle ==="
            docker compose exec -T web grep -o "Description" /app/frontend/dist/assets/*.js | wc -l

            echo "=== Recent logs ==="
            docker compose logs --tail=20 web
          EOF