"""Radios mac

Revision ID: 08d00be587e2
Revises: 0c2701e15b02
Create Date: 2025-03-31 12:13:18.962196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08d00be587e2'
down_revision = '0c2701e15b02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('radios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mac', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('radios', schema=None) as batch_op:
        batch_op.drop_column('mac')

    # ### end Alembic commands ###
