"""migration for pref file location

Revision ID: 0976269ab6b1
Revises: 63bbfd33d8f6
Create Date: 2024-07-02 22:58:07.513626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0976269ab6b1'
down_revision = '63bbfd33d8f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('takprofiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('takPrefFileLocation', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('takprofiles', schema=None) as batch_op:
        batch_op.drop_column('takPrefFileLocation')

    # ### end Alembic commands ###
