"""Radios

Revision ID: 0c2701e15b02
Revises: 230a3579eadd
Create Date: 2025-01-31 10:25:48.429473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c2701e15b02'
down_revision = '230a3579eadd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('radioType', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('softwareVersion', sa.String(), nullable=True),
    sa.Column('model', sa.Integer(), nullable=True),
    sa.Column('vendor', sa.Integer(), nullable=True),
    sa.Column('shortName', sa.String(), nullable=True),
    sa.Column('longName', sa.String(), nullable=True),
    sa.Column('assignedTo', sa.Integer(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignedTo'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('radios')
    # ### end Alembic commands ###
