"""Add autoApprove to onboarding codes

Revision ID: 10396f2932d0
Revises: a1b2c3d4e5f6
Create Date: 2026-01-22 15:10:15.471305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10396f2932d0'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onboardingcodes', sa.Column('autoApprove', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('onboardingcodes', 'autoApprove')
    # ### end Alembic commands ###
