"""Radios privkey

Revision ID: 3b550486a38f
Revises: 87202649edf5
Create Date: 2025-04-01 16:21:37.538968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b550486a38f'
down_revision = '87202649edf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radios', sa.Column('privateKey', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radios', 'privateKey')
    # ### end Alembic commands ###
