"""Add requireApproval and approver fields to onboarding codes

Revision ID: 52971f895ad8
Revises: 10396f2932d0
Create Date: 2026-01-22 15:17:19.828081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52971f895ad8'
down_revision = '10396f2932d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approver_onboardingcode_association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('onboardingcode_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['onboardingcode_id'], ['onboardingcodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )

    # Use batch mode for SQLite compatibility
    with op.batch_alter_table('onboardingcodes') as batch_op:
        batch_op.add_column(sa.Column('requireApproval', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('approverRoleId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_onboardingcodes_approverRoleId', 'user_roles', ['approverRoleId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboardingcodes') as batch_op:
        batch_op.drop_constraint('fk_onboardingcodes_approverRoleId', type_='foreignkey')
        batch_op.drop_column('approverRoleId')
        batch_op.drop_column('requireApproval')
    op.drop_table('approver_onboardingcode_association')
    # ### end Alembic commands ###
