"""OnboardingCodes

Revision ID: 5913094e5da3
Revises: 7881b5c175b1
Create Date: 2024-06-28 00:29:15.879635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5913094e5da3'
down_revision = '7881b5c175b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboardingcodes', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('ownedByUser',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('ownedByRole',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('uses',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('maxUses',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboardingcodes', schema=None) as batch_op:
        batch_op.alter_column('maxUses',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('uses',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('ownedByRole',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('ownedByUser',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
