"""migrations for takprofile

Revision ID: 63bbfd33d8f6
Revises: 63de76ba6fbd
Create Date: 2024-06-29 08:53:54.844207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63bbfd33d8f6'
down_revision = '63de76ba6fbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('takprofiles', schema=None) as batch_op:
        batch_op.alter_column('isPublic',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('takTemplateFolderLocation',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('takprofiles', schema=None) as batch_op:
        batch_op.alter_column('takTemplateFolderLocation',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('isPublic',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
