"""yamlconfig

Revision ID: 6ccf5d0adcfd
Revises: 7ee53d89757e
Create Date: 2025-04-01 16:58:57.563609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ccf5d0adcfd'
down_revision = '7ee53d89757e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meshtastic', sa.Column('yamlConfig', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meshtastic', 'yamlConfig')
    # ### end Alembic commands ###
