"""Onboarded By

Revision ID: 7881b5c175b1
Revises: bfc6bcc4e980
Create Date: 2024-06-28 00:02:00.782452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7881b5c175b1'
down_revision = 'bfc6bcc4e980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboardedBy', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('onboardedBy')

    # ### end Alembic commands ###
