"""radio created at and updated at

Revision ID: 7ee53d89757e
Revises: 3b550486a38f
Create Date: 2025-04-01 16:25:56.499669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ee53d89757e'
down_revision = '3b550486a38f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radios', sa.Column('createdAt', sa.DateTime(), nullable=True))
    op.add_column('radios', sa.Column('updatedAt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radios', 'updatedAt')
    op.drop_column('radios', 'createdAt')
    # ### end Alembic commands ###
