"""Radios pubkey and role

Revision ID: 87202649edf5
Revises: ddf5de26b736
Create Date: 2025-03-31 14:37:47.824869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87202649edf5'
down_revision = 'ddf5de26b736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radios', sa.Column('role', sa.String(), nullable=True))
    op.add_column('radios', sa.Column('publicKey', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radios', 'publicKey')
    op.drop_column('radios', 'role')
    # ### end Alembic commands ###
