"""Taksettings

Revision ID: 9bfec0f01002
Revises: 47617b1a80ce
Create Date: 2024-06-27 18:04:43.974192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bfec0f01002'
down_revision = '47617b1a80ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboardingcodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('onboardingCode', sa.String(), nullable=False),
    sa.Column('ownedByUser', sa.Boolean(), nullable=False),
    sa.Column('ownedByRole', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_onboardingcode_association',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('onboardingcode_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['onboardingcode_id'], ['onboardingcodes.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['user_roles.id'], )
    )
    op.create_table('taksettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('takProfileID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['takProfileID'], ['takprofiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_onboardingcode_association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('onboardingcode_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['onboardingcode_id'], ['onboardingcodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_table('tak_settings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tak_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('key', sa.VARCHAR(), nullable=False),
    sa.Column('value', sa.VARCHAR(), nullable=False),
    sa.Column('takProfileID', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['takProfileID'], ['takprofiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_onboardingcode_association')
    op.drop_table('taksettings')
    op.drop_table('role_onboardingcode_association')
    op.drop_table('onboardingcodes')
    # ### end Alembic commands ###
