"""User Expiry

Revision ID: 9cf7ffd114fc
Revises: 0976269ab6b1
Create Date: 2024-08-14 19:08:21.183796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cf7ffd114fc'
down_revision = '0976269ab6b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboardingcodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userExpiryDate', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiryDate', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('expiryDate')

    with op.batch_alter_table('onboardingcodes', schema=None) as batch_op:
        batch_op.drop_column('userExpiryDate')

    # ### end Alembic commands ###
