"""Add approval workflow fields to pending registrations

Revision ID: aafd21c9ae8e
Revises: 52971f895ad8
Create Date: 2026-01-22 15:20:31.279927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aafd21c9ae8e'
down_revision = '52971f895ad8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table('pending_registrations') as batch_op:
        batch_op.add_column(sa.Column('approval_status', sa.String(), nullable=False, server_default='pending_verification'))
        batch_op.add_column(sa.Column('approval_token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_pending_registrations_approval_token', ['approval_token'])
        batch_op.create_foreign_key('fk_pending_registrations_approved_by', 'users', ['approved_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_registrations') as batch_op:
        batch_op.drop_constraint('fk_pending_registrations_approved_by', type_='foreignkey')
        batch_op.drop_constraint('uq_pending_registrations_approval_token', type_='unique')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('approval_token')
        batch_op.drop_column('approval_status')
    # ### end Alembic commands ###
