"""one time link system.

Revision ID: bfc6bcc4e980
Revises: b39ebfc5e342
Create Date: 2024-06-27 23:59:29.938681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfc6bcc4e980'
down_revision = 'b39ebfc5e342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboardingcodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uses', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('maxUses', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboardingcodes', schema=None) as batch_op:
        batch_op.drop_column('maxUses')
        batch_op.drop_column('uses')

    # ### end Alembic commands ###
