"""Add email verification and pending registrations

Revision ID: d52f4586db0e
Revises: 61fcea25eab2
Create Date: 2025-10-16 23:56:32.263526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd52f4586db0e'
down_revision = '61fcea25eab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create pending_registrations table
    op.create_table('pending_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('callsign', sa.String(), nullable=True),
    sa.Column('onboarding_code_id', sa.Integer(), nullable=False),
    sa.Column('verification_token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['onboarding_code_id'], ['onboardingcodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('verification_token')
    )

    # Use batch mode for SQLite to rename column in onboardingcodes
    # First add the new column
    with op.batch_alter_table('onboardingcodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboardContactId', sa.Integer(), nullable=True))

    # Copy data from old column to new column
    op.execute('UPDATE onboardingcodes SET onboardContactId = onboardContact WHERE onboardContact IS NOT NULL')

    # Now drop old column and add constraints
    with op.batch_alter_table('onboardingcodes', schema=None) as batch_op:
        batch_op.create_foreign_key('onboardingcodes_onboardContactId_fkey', 'users', ['onboardContactId'], ['id'])
        batch_op.drop_column('onboardContact')

    # Update radios table types
    with op.batch_alter_table('radios', schema=None) as batch_op:
        batch_op.alter_column('model',
                   existing_type=sa.INTEGER(),
                   type_=sa.String(),
                   existing_nullable=True)
        batch_op.alter_column('vendor',
                   existing_type=sa.INTEGER(),
                   type_=sa.String(),
                   existing_nullable=True)

    # Add emailVerified column to users
    op.add_column('users', sa.Column('emailVerified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'emailVerified')

    with op.batch_alter_table('radios', schema=None) as batch_op:
        batch_op.alter_column('vendor',
                   existing_type=sa.String(),
                   type_=sa.INTEGER(),
                   existing_nullable=True)
        batch_op.alter_column('model',
                   existing_type=sa.String(),
                   type_=sa.INTEGER(),
                   existing_nullable=True)

    with op.batch_alter_table('onboardingcodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboardContact', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('onboardingcodes_onboardContactId_fkey', type_='foreignkey')
        batch_op.create_foreign_key('onboardingcodes_onboardContact_fkey', 'users', ['onboardContact'], ['id'])
        batch_op.drop_column('onboardContactId')

    op.drop_table('pending_registrations')
    # ### end Alembic commands ###
