"""Meshtastic isPublic

Revision ID: ed29579e0646
Revises: f41b8eb38bf2
Create Date: 2024-08-19 12:13:16.939790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed29579e0646'
down_revision = 'f41b8eb38bf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meshtastic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isPublic', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meshtastic', schema=None) as batch_op:
        batch_op.drop_column('isPublic')

    # ### end Alembic commands ###
