"""Meshtastic

Revision ID: f41b8eb38bf2
Revises: acb23fb7c062
Create Date: 2024-08-19 10:53:31.715399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f41b8eb38bf2'
down_revision = 'acb23fb7c062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meshtastic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role_meshtastic_association',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('meshtastic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meshtastic_id'], ['meshtastic.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['user_roles.id'], )
    )
    op.create_table('user_meshtastic_association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('meshtastic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meshtastic_id'], ['meshtastic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_meshtastic_association')
    op.drop_table('role_meshtastic_association')
    op.drop_table('meshtastic')
    # ### end Alembic commands ###
